applications:
    front:
        type: apache
        links: [app]
        ports:
            8080: 80
        volumes:
            .: /var/www
        custom:
            fastCgi: app
            documentRoot: /var/www/web
            modules: [rewrite]

    app:
        type: php-fpm
        links: [jackrabbit]
        apt_get: [php5-gd, php5-intl]
        before_script: rm -rf /var/www/app/cache/*
        ports:
            9000: 9000
        volumes:
            .: /var/www
        custom:
            modules: []

    jackrabbit:
        type: jackrabbit
        ports:
            8082: 8082
        volumes:
            .gaudi/jackrabbit: /opt/jackrabbit/jackrabbit
            
binaries:
    composer:
        type: composer


# gaudi run composer create-project symfony-cmf/standard-edition sf/ ~1.1
# mv sf/* .
# echo "<?php $container->setParameter('database_host', getenv('DB_PORT_3306_TCP_ADDR'));" > app/config/parameters.php
# gaudi
